In [1]:
%pip install --upgrade pandas

Requirement already satisfied: pandas in d:\Anaconda\envs\biostruct\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in d:\Anaconda\envs\biostruct\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\Anaconda\envs\biostruct\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\Anaconda\envs\biostruct\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in d:\Anaconda\envs\biostruct\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 3.0.5

In [3]:
df = pd.read_csv('brca_metabric/data_clinical_patient.txt', sep='\t', comment='#')
#sep='\t' specifies that the file is tab-separated, and comment='#' indicates that lines starting with '#' should be treated as comments and ignored.
clinical_patient = df
display(clinical_patient.head(n=10))

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,...,OS_STATUS,CLAUDIN_SUBTYPE,THREEGENE,VITAL_STATUS,LATERALITY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE,BREAST_SURGERY,RFS_MONTHS,RFS_STATUS
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,...,0:LIVING,claudin-low,ER-/HER2-,Living,Right,YES,Ductal/NST,MASTECTOMY,140.500000,0:Not Recurred
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,...,0:LIVING,LumA,ER+/HER2- High Prolif,Living,Right,YES,Ductal/NST,BREAST CONSERVING,84.633333,0:Not Recurred
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,...,1:DECEASED,LumB,NaN,Died of Disease,Right,NO,Ductal/NST,MASTECTOMY,153.300000,1:Recurred
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,...,0:LIVING,LumB,NaN,Living,Right,YES,Mixed,MASTECTOMY,164.933333,0:Not Recurred
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,...,1:DECEASED,LumB,ER+/HER2- High Prolif,Died of Disease,Right,YES,Mixed,MASTECTOMY,18.800000,1:Recurred
5,MB-0010,0.0,4.062,Moderate,NO,1.0,Positve,NEUTRAL,YES,Post,...,1:DECEASED,LumB,ER+/HER2- High Prolif,Died of Disease,Left,YES,Ductal/NST,MASTECTOMY,2.933333,1:Recurred
6,MB-0014,1.0,4.020,Moderate,YES,1.0,Positve,LOSS,YES,Post,...,0:LIVING,LumB,NaN,Living,Right,YES,Ductal/NST,BREAST CONSERVING,164.333333,0:Not Recurred
7,MB-0020,NaN,6.130,High,YES,1.0,Negative,NEUTRAL,NO,Post,...,1:DECEASED,Normal,ER-/HER2-,Died of Disease,Left,YES,Lobular,MASTECTOMY,11.900000,1:Recurred
8,MB-0022,1.0,4.058,Moderate,NO,1.0,Positve,NEUTRAL,YES,Post,...,1:DECEASED,claudin-low,NaN,Died of Other Causes,Left,YES,Mixed,BREAST CONSERVING,99.533333,0:Not Recurred
9,MB-0025,11.0,6.680,NaN,NaN,1.0,Positve,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Ductal/NST,NaN,128.000000,1:Recurred

In [4]:
# the following line will display the summary information of the clinical_patient DataFrame, including the number of non-null entries, data types, and memory usage.
clinical_patient.info()

<class 'pandas.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PATIENT_ID                     2509 non-null   str
 1   LYMPH_NODES_EXAMINED_POSITIVE  2243 non-null   float64
 2   NPI                            2287 non-null   float64
 3   CELLULARITY                    1917 non-null   str
 4   CHEMOTHERAPY                   1980 non-null   str
 5   COHORT                         2498 non-null   float64
 6   ER_IHC                         2426 non-null   str
 7   HER2_SNP6                      1980 non-null   str
 8   HORMONE_THERAPY                1980 non-null   str
 9   INFERRED_MENOPAUSAL_STATE      1980 non-null   str
 10  SEX                            2509 non-null   str
 11  INTCLUST                       1980 non-null   str
 12  AGE_AT_DIAGNOSIS               2498 non-null   float64
 13  OS_MONTHS                      1981 non-null   float64
 14  OS_STATUS                      1981 non-null   str
 15  CLAUDIN_SUBTYPE                1980 non-null   str
 16  THREEGENE                      1764 non-null   str
 17  VITAL_STATUS                   1980 non-null   str
 18  LATERALITY                     1870 non-null   str
 19  RADIO_THERAPY                  1980 non-null   str
 20  HISTOLOGICAL_SUBTYPE           2374 non-null   str
 21  BREAST_SURGERY                 1955 non-null   str
 22  RFS_MONTHS                     2388 non-null   float64
 23  RFS_STATUS                     2488 non-null   str
dtypes: float64(6), str(18)
memory usage: 470.6 KB

In [5]:
# Subset the dataframe
#.copy() is used to create a new DataFrame that is a copy of the selected columns from the original DataFrame. This is important to avoid SettingWithCopyWarning in pandas, which can occur when trying to modify a slice of a DataFrame.
clinical_baseline = clinical_patient.copy()
display(clinical_baseline.head())

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,...,OS_STATUS,CLAUDIN_SUBTYPE,THREEGENE,VITAL_STATUS,LATERALITY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE,BREAST_SURGERY,RFS_MONTHS,RFS_STATUS
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,...,0:LIVING,claudin-low,ER-/HER2-,Living,Right,YES,Ductal/NST,MASTECTOMY,140.500000,0:Not Recurred
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,...,0:LIVING,LumA,ER+/HER2- High Prolif,Living,Right,YES,Ductal/NST,BREAST CONSERVING,84.633333,0:Not Recurred
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,...,1:DECEASED,LumB,NaN,Died of Disease,Right,NO,Ductal/NST,MASTECTOMY,153.300000,1:Recurred
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,...,0:LIVING,LumB,NaN,Living,Right,YES,Mixed,MASTECTOMY,164.933333,0:Not Recurred
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,...,1:DECEASED,LumB,ER+/HER2- High Prolif,Died of Disease,Right,YES,Mixed,MASTECTOMY,18.800000,1:Recurred

In [6]:
# 1. Define the target variable (y) from the clean clinical_patient DataFrame.
y = clinical_baseline['CLAUDIN_SUBTYPE']

# 2. Define the feature matrix (X) by dropping the columns that are not needed for the model.
cols_to_drop = [
    'PATIENT_ID',
    'CLAUDIN_SUBTYPE',  # Target variable
    'THREEGENE', 'COHORT', 'HER2_SNP6',  # Target leakage
    'OS_MONTHS', 'OS_STATUS',
    'RFS_MONTHS', 'RFS_STATUS', 'VITAL_STATUS',  # Endpoints / Validation
    'SEX'  # Uninformative constant
]

# 3. Create feature matrix (X) by dropping the specified columns from the clean clinical_patient DataFrame.
X = clinical_baseline.drop(columns=cols_to_drop, inplace=False) #inplace=False ensures that the original DataFrame is not modified, and a new DataFrame is returned instead.
display(X.head(n=10))

,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,ER_IHC,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,INTCLUST,AGE_AT_DIAGNOSIS,LATERALITY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE,BREAST_SURGERY
0,10.0,6.044,NaN,NO,Positve,YES,Post,4ER+,75.65,Right,YES,Ductal/NST,MASTECTOMY
1,0.0,4.020,High,NO,Positve,YES,Pre,4ER+,43.19,Right,YES,Ductal/NST,BREAST CONSERVING
2,1.0,4.030,High,YES,Positve,YES,Pre,3,48.87,Right,NO,Ductal/NST,MASTECTOMY
3,3.0,4.050,Moderate,YES,Positve,YES,Pre,9,47.68,Right,YES,Mixed,MASTECTOMY
4,8.0,6.080,High,YES,Positve,YES,Post,9,76.97,Right,YES,Mixed,MASTECTOMY
5,0.0,4.062,Moderate,NO,Positve,YES,Post,7,78.77,Left,YES,Ductal/NST,MASTECTOMY
6,1.0,4.020,Moderate,YES,Positve,YES,Post,3,56.45,Right,YES,Ductal/NST,BREAST CONSERVING
7,NaN,6.130,High,YES,Negative,NO,Post,4ER-,70.00,Left,YES,Lobular,MASTECTOMY
8,1.0,4.058,Moderate,NO,Positve,YES,Post,3,89.08,Left,YES,Mixed,BREAST CONSERVING
9,11.0,6.680,NaN,NaN,Positve,NaN,NaN,NaN,76.24,NaN,NaN,Ductal/NST,NaN

In [7]:
print("Shape of feature matrix (X):", X.shape)

print("Shape of target variable (y):", y.shape)
print("Target class counts:\n", y.value_counts())
print(y.value_counts(normalize=True))  # Display class distribution as percentages
print(y.value_counts(dropna=False))  # Display class distribution including NaN values
display(X.head(n=10))

Shape of feature matrix (X): (2509, 13)
Shape of target variable (y): (2509,)
Target class counts:
 CLAUDIN_SUBTYPE
LumA           700
LumB           475
Her2           224
claudin-low    218
Basal          209
Normal         148
NC               6
Name: count, dtype: int64
CLAUDIN_SUBTYPE
LumA           0.353535
LumB           0.239899
Her2           0.113131
claudin-low    0.110101
Basal          0.105556
Normal         0.074747
NC             0.003030
Name: proportion, dtype: float64
CLAUDIN_SUBTYPE
LumA           700
NaN            529
LumB           475
Her2           224
claudin-low    218
Basal          209
Normal         148
NC               6
Name: count, dtype: int64

,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,ER_IHC,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,INTCLUST,AGE_AT_DIAGNOSIS,LATERALITY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE,BREAST_SURGERY
0,10.0,6.044,NaN,NO,Positve,YES,Post,4ER+,75.65,Right,YES,Ductal/NST,MASTECTOMY
1,0.0,4.020,High,NO,Positve,YES,Pre,4ER+,43.19,Right,YES,Ductal/NST,BREAST CONSERVING
2,1.0,4.030,High,YES,Positve,YES,Pre,3,48.87,Right,NO,Ductal/NST,MASTECTOMY
3,3.0,4.050,Moderate,YES,Positve,YES,Pre,9,47.68,Right,YES,Mixed,MASTECTOMY
4,8.0,6.080,High,YES,Positve,YES,Post,9,76.97,Right,YES,Mixed,MASTECTOMY
5,0.0,4.062,Moderate,NO,Positve,YES,Post,7,78.77,Left,YES,Ductal/NST,MASTECTOMY
6,1.0,4.020,Moderate,YES,Positve,YES,Post,3,56.45,Right,YES,Ductal/NST,BREAST CONSERVING
7,NaN,6.130,High,YES,Negative,NO,Post,4ER-,70.00,Left,YES,Lobular,MASTECTOMY
8,1.0,4.058,Moderate,NO,Positve,YES,Post,3,89.08,Left,YES,Mixed,BREAST CONSERVING
9,11.0,6.680,NaN,NaN,Positve,NaN,NaN,NaN,76.24,NaN,NaN,Ductal/NST,NaN

In [8]:
# Check for missing values in the feature matrix (X)
missing_values = X.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 LYMPH_NODES_EXAMINED_POSITIVE    266
NPI                              222
CELLULARITY                      592
CHEMOTHERAPY                     529
ER_IHC                            83
HORMONE_THERAPY                  529
INFERRED_MENOPAUSAL_STATE        529
INTCLUST                         529
AGE_AT_DIAGNOSIS                  11
LATERALITY                       639
RADIO_THERAPY                    529
HISTOLOGICAL_SUBTYPE             135
BREAST_SURGERY                   554
dtype: int64

In [9]:
# Cleaning the feature matrix (X) without dropping any columns